### ISSUE TITLE
Button is alos shown in read-only mode

### ISSUE THREAD

**Issue by rugk** [LokeshN/ep_foot_note#3]
When I show an etherpad in read-only mode all edit buttons are hidden - except the "FN" one.

![footnote](https://cloud.githubusercontent.com/assets/11966684/15018780/7171f5f8-121b-11e6-98ad-2120568edaaf.png)

The button should not only be disabled, but completely hidden.

**Comment by LokeshN** [comment]
@rugk Thanks for reporting the issue. I have fixed it and pushed to npm also.
